version: '3'

services:
  redis:
    image: redis:4
    ports:
      - "6379:6379"
  mysql:
    image: mariadb:10.2
    environment:
      MYSQL_DATABASE: dataflow
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
  rabbitmq:
    image: rabbitmq:3.7-management
    ports:
      - "5672:5672"
      - "15671-15672:15671-15672"
